# -*- coding: utf-8 -*-
"""Police_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ukFjbSbfolM3ggpco68oaKbaYcRamIf_

# **Big Data Analysis using pyhton**
"""

import pandas as pd
df=pd.read_csv('/content/3. Police Data.csv')

df

"""1.Romoving the column that contains missing values"""

df.isnull().sum()

df.drop(columns='country_name',inplace=True)

df

"""2.For speeding , where men or women stopped more often ?"""

df.head()

df[df.violation == 'Speeding'].driver_gender.value_counts()

"""3.Does gender affect who gets searched during a stop?"""

df.head()

df.groupby('driver_gender').search_conducted.sum()

df.search_conducted.value_counts()

"""4. What is the mean stop_duration?"""

df.head()

df.stop_duration.value_counts()

df['stop_duration']=df['stop_duration'].map({'0-15 Min':7.5,'16-30 Min':24 ,'30+ Min':45,})
df['stop_duration']

df['stop_duration'].mean()

"""5.Compare the age distribution for each violation"""

df.groupby('violation').driver_age.describe()